### ISSUE TITLE
Achieve same front-page post layout as the original Fairy

### ISSUE THREAD

**Issue by oleteacher** [danpros/fairy#2]
Thanks for porting this theme!

I cannot get the front-page posts to show the post image like:
![image](https://github.com/danpros/fairy/assets/26278259/345e215c-a0f0-42c9-aae7-5e93edc2731b)

If I set to full post, the image appears, but when setting to summary the image is removed:
![image](https://github.com/danpros/fairy/assets/26278259/1d14058d-fc0e-44f8-900d-13bf780bcb04)

Am I missing a setting? Really like to have the image appear, nice visual candy :)

**Comment by oleteacher** [comment]
I had a brain fart. Recalled that using the `<!--image http://www.example.com/image-url/image.jpg image-->` might solve the issue and it did.

Thank you again for porting this theme to HTMLY!

**Comment by danpros** [comment]
Great you solved it. Create a post with featured image so you do not need to add it manually.

**Comment by 2braincells2go** [comment]
I discovered sometime back that the featured image option in the post area does not appear until you add `<!--image http://www.example.com/image-url/image.jpg image-->` to the post content. Then I discovered that simply doing as Dan pointed out saves the extra step :)

**Comment by danpros** [comment]
And if you don't like the featured image at the top when visiting the post, just edit `post.html.php` and cut paste any where:

```php
<?php if (!empty($p->image)):?>
<figure class="post-thumbnail card_media">
	<img src="<?php echo $p->image; ?>"/>                
</figure>
<?php endif;?>
```

Eg. display featured above the content, and below the meta, becomes:

```php
<div class="entry-content">
	<?php if (!empty($p->image)):?>
	<figure class="post-thumbnail card_media">
		<img src="<?php echo $p->image; ?>"/>                
	</figure>
	<?php endif;?>
	<?php echo $p->body; ?>
</div>
```

**Comment by oleteacher** [comment]
Thank you @danpros and @2braincells2go! Appreciate the info and tips.
